server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gateway_console?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 290616
logging:
  config: classpath:log4j.properties
  level:
    root: off
    com.cn.petshome.paymentgateway.mapper: debug
    org:
      springframework: off
mybatis:
  mapper-locations: classpath:mapper-config/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
